apiVersion: v1
kind: Service
metadata:
  name: webserver-nodeport
  labels:
    app: webserver

spec:
  type: NodePort
  selector:
    app: webserver
  ports:
  - port: 80
    targetPort: 80 
    nodePort: 31000
---

apiVersion: v1
kind: Service
metadata:
  name: systeminfo-nodeport
  labels:
    app: systeminfo

spec:
  type: NodePort
  sessionAffinity: None
  selector:
    app: systeminfo
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32000
    
