apiVersion: v1
kind: Service
metadata:
  name: webserver-clusterip
  labels:
    app: webserver

spec:
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: webserver
  ports:
  - port: 80
    targetPort: 80 
---

apiVersion: v1
kind: Service
metadata:
  name: systeminfo-clusterip
  labels:
    app: systeminfo

spec:
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: systeminfo
  ports:
  - port: 8080
    targetPort: 8080



