---
- name: Install Kubernetes on Primary Control Plane
  hosts: control_plane_primary
  gather_facts: false
  vars:
    instance_id: "{{ control_plane_primary_instance_id }}"
    region_name: "{{ region_name }}"
  tasks:
    - name: Install Kubernetes on Primary Control Plane
      command: >
        aws ssm send-command
        --document-name 'AWS-RunShellScript'
        --instance-ids '{{ instance_id }}'
        --parameters 'commands=[
        "echo 'Installing Kubernetes Cluster...'",
        # Add Kubernetes installation commands here
        ]'
        --region '{{ region_name }}'
      register: ssm_output_primary

    - debug:
        var: ssm_output_primary
