- name: Smoke Test for Kubernetes Cluster EC2 Instances
  hosts: all
  tasks:
    - name: Create a sample log file in /tmp directory
      ansible.builtin.file:
        path: /tmp/k8s_setup.log
        state: touch
        mode: '0644'
