- name: # Kubernetes cluster initialization
  gather_facts: false
  hosts: control_planes
  tasks:
  - name: # 1. download network topology...
    shell: | 
      wget https://raw.githubusercontent.com/projectcalico/calico/v3.24.0/manifests/calico.yaml

  - name: # 2. initializing kubernetes cluster on `pwd`...
    shell: | 
      sudo kubeadm init      
    register: mylogs_2
  - debug: msg="{{mylogs_2.stdout_lines}}"
  - debug: msg="{{mylogs_2.stderr_lines}}"  

  - name: # 3. configure the account on the ControlPlane Node to have admin access to the API server from a non-privileged account.
    shell: | 
      mkdir -p $HOME/.kube
      sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
      sudo chown $(id -u):$(id -g) $HOME/.kube/config      
 
  - name: # 4. create POD network...
    shell: | 
      kubectl apply -f calico.yaml
      kubectl taint nodes --all node-role.kubernetes.io/control-plane-
      sleep 2m     
    register: mylogs_4
  - debug: msg="{{mylogs_4.stdout_lines}}"
  - debug: msg="{{mylogs_4.stderr_lines}}"

  - name: # 5. Kubernetes POD status check
    shell: | 
      kubectl get pods --all-namespaces    
    register: mylogs_5
  - debug: msg="{{mylogs_5.stdout_lines}}"
  - debug: msg="{{mylogs_5.stderr_lines}}"

  