- name: # Kubernetes installation
  gather_facts: false
  hosts: kubernetes_cluster
  tasks:
  - name: # 1. installing Kubernetes...
    shell: | 
      cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
      enabled=1
      gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      exclude=kubelet kubeadm kubectl
      EOF

      sudo setenforce 0
      sudo sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config

      sudo yum install kubelet kubeadm kubectl --disableexcludes=kubernetes -y
      sudo systemctl enable --now kubelet
      sudo yum versionlock add kubelet kubeadm kubectl containerd      

      sudo systemctl enable kubelet.service      
    register: mylogs_1
  - debug: msg="{{mylogs_1.stdout_lines}}"
  - debug: msg="{{mylogs_1.stderr_lines}}"  


