- name: # Pre-installing packages required for Kubernetes
  gather_facts: false
  hosts: kubernetes_cluster
  tasks:
  - name: # 0. confirm hostname change
    shell: | 
      echo "hostname: $(hostname)"

  - name: # 1. enabling kernal modules...
    shell: | 
      sudo modprobe overlay
      sudo modprobe br_netfilter
  
  - name: # 2. setting up networking...
    shell: | 
      cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1
      EOF

      sudo sysctl --system
    register: mylogs_2
  - debug: msg="{{mylogs_2.stdout_lines}}"
  - debug: msg="{{mylogs_2.stderr_lines}}"  

  - name: # 3. install & configure Containerd(docker alternative)...
    shell: | 
      sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      sudo yum install -y containerd

      sudo mkdir -p /etc/containerd
      sudo containerd config default | sudo tee /etc/containerd/config.toml
      sudo sed -i 's/            SystemdCgroup = false/            SystemdCgroup = true/' /etc/containerd/config.toml
      sudo systemctl restart containerd
      sudo systemctl enable containerd.service      
    register: mylogs_3
  - debug: msg="{{mylogs_3.stdout_lines}}"
  - debug: msg="{{mylogs_3.stderr_lines}}"   

