package client_no_aws;

import client_no_aws.crypto.AesEncryptor;
import client_no_aws.crypto.RsaEncryptor;
import org.junit.jupiter.api.*;

import java.io.FileOutputStream;
import java.io.OutputStream;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Properties;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Third Party Client Encryption Test (Use-Case 1)
 *
 * Simulates a 3rd party client WITHOUT AWS account.
 * Uses standard Java crypto (NO AWS SDK).
 *
 * Flow:
 * 1. Load public key from resources (received via secure email from company)
 * 2. Generate random DEK and encrypt data with AES-GCM
 * 3. Encrypt DEK with public key (RSA-OAEP)
 * 4. Save encrypted data to properties file for decryption test
 *
 * Prerequisites:
 * - Download public key from AWS KMS and place in src/test/resources/public-key.pem
 * - Command: aws kms get-public-key --key-id alias/test_asymmetric_kms-... --region us-east-1 --profile dev --output text --query PublicKey | base64 -d > public-key.der
 *   Then convert to PEM format or use AWS Console to download
 */
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class ThirdPartyClientEncryptionTest {

  private static final String PROPERTIES_FILE = "src/test/resources/_temp/encryption-data.properties";

  private final AesEncryptor aesEncryptor = new AesEncryptor();
  private final RsaEncryptor rsaEncryptor = new RsaEncryptor();

  @Test
  @Order(1)
  @DisplayName("Load public key from resources - PEM file exists")
  void testLoadPublicKeyFromResources() throws Exception {
    rsaEncryptor.loadPublicKeyFromResources();
    System.out.println("✓ Public key loaded from src/test/resources/public-key.pem");
  }

  @Test
  @Order(2)
  @DisplayName("Full encryption flow - Encrypt and save to properties file")
  void testFullEncryptionFlow() throws Exception {
    // === Step 1: Load public key from resources ===
    System.out.println("\n=== Step 1: Load Public Key from Resources ===");

    rsaEncryptor.loadPublicKeyFromResources();
    System.out.println("✓ Public key loaded from src/test/resources/public-key.pem");

    // === Step 2: Encrypt data with AES-GCM ===
    System.out.println("\n=== Step 2: Encrypt Data (AES-GCM) ===");

    String sensitiveData = "This is confidential data from 3rd party client!";
    System.out.println("Original data: \"" + sensitiveData + "\"");

    // Generate random DEK
    byte[] dek = aesEncryptor.generateDek();
    System.out.println("✓ Generated random 256-bit DEK");

    // Encrypt data with DEK
    AesEncryptor.EncryptionResult aesResult = aesEncryptor.encrypt(sensitiveData, dek);
    System.out.println("✓ Data encrypted with AES-GCM");
    System.out.println("  Encrypted data (Base64): " + truncate(aesResult.encryptedDataBase64(), 50));
    System.out.println("  IV (Base64): " + aesResult.ivBase64());
    System.out.println("  Auth Tag (Base64): " + aesResult.authTagBase64());

    // === Step 3: Encrypt DEK with public key (RSA-OAEP) ===
    System.out.println("\n=== Step 3: Encrypt DEK (RSA-OAEP) ===");

    String encryptedDek = rsaEncryptor.encryptDek(dek);
    System.out.println("✓ DEK encrypted with company's public key");
    System.out.println("  Encrypted DEK (Base64): " + truncate(encryptedDek, 50));

    // === Step 4: Save encrypted data to properties file ===
    System.out.println("\n=== Step 4: Save to Properties File ===");

    Properties props = new Properties();
    props.setProperty("encryptedDek", encryptedDek);
    props.setProperty("encryptedData", aesResult.encryptedDataBase64());
    props.setProperty("iv", aesResult.ivBase64());
    props.setProperty("authTag", aesResult.authTagBase64());
    props.setProperty("originalData", sensitiveData);

    Path propsPath = Paths.get(PROPERTIES_FILE);
    try (OutputStream os = new FileOutputStream(propsPath.toFile())) {
      props.store(os, "Encryption data for decryption test - Generated by ThirdPartyClientEncryptionTest");
    }

    System.out.println("✓ Encryption data saved to: " + PROPERTIES_FILE);
    System.out.println("\n✓ SUCCESS: Encryption complete. Run CompanyBackendDecryptionTest to verify decryption.");
  }

  private String truncate(String str, int maxLen) {
    return str.length() > maxLen ? str.substring(0, maxLen) + "..." : str;
  }
}
